service: mono-repo-js-service

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

